contact_info = {'location': {'latitude': 99.0124, 'longitude': -100.1471}, 'email': 'captainamerica@yahoo.com',
                'phone': '123-456-7890',
                'postal_address': {'address_line': '3', 'country_code': 'US', 'postal_code': '98765',
                                   'region': 'GM', 'municipality': 'Agrabah',
                                   'short_display_address': 'Agrabah, GM, US'},
                'image_url': 'https://www.syfy.com/sites/syfy/files/styles/1200x680/public/2019/06/spider-man-original.jpg',
                'name': {'formatted_name': 'Clark L Kent', 'family_name': 'Kent', 'middle_name': 'L',
                         'given_name': 'Clark'}}

contact_info_no_phone = {'location': {'latitude': 99.0124, 'longitude': -100.1471}, 'email': 'captainamerica@yahoo.com',
                         'phone': None,
                         'postal_address': {'address_line': '3', 'country_code': 'US', 'postal_code': '98765',
                                            'region': 'GM', 'municipality': 'Agrabah',
                                            'short_display_address': 'Agrabah, GM, US'},
                         'image_url': 'https://www.syfy.com/sites/syfy/files/styles/1200x680/public/2019/06/spider-man-original.jpg',
                         'name': {'formatted_name': 'Clark L Kent', 'family_name': 'Kent', 'middle_name': 'L',
                                  'given_name': 'Clark'}}

contact_info_no_contact_info = {'location': {'latitude': 99.0124, 'longitude': -100.1471}, 'email': None,
                                'phone': None,
                                'postal_address': {'address_line': '3', 'country_code': 'US', 'postal_code': '98765',
                                                   'region': 'GM', 'municipality': 'Agrabah',
                                                   'short_display_address': 'Agrabah, GM, US'},
                                'image_url': 'https://www.syfy.com/sites/syfy/files/styles/1200x680/public/2019/06/spider-man-original.jpg',
                                'name': {'formatted_name': 'Clark L Kent', 'family_name': 'Kent', 'middle_name': 'L',
                                         'given_name': 'Clark'}}

linkedin_info = [{'Email': 'captainamerica@yahoo.com', 'Phone Number': '1234567890',
                  'Linkedin': 'https://linkedin.com/in/captainamerica'},
                 {'Email': '', 'Phone Number': '5555555555',
                  'Linkedin': 'https://linkedin.com/in/BruceWayne-12345'},
                 {'Email': '', 'Phone Number': '999888777',
                  'Linkedin': 'https://linkedin.com/in/PeterParker-23456'},
                 {'Email': 'Heisenberg@hotmail.com', 'Phone Number': '6666666666',
                  'Linkedin': 'https://linkedin.com/in/Walter-White-878262'}]

expected_candidates = ['Hello Clark Kent\n'
                       'Linkedin: https://linkedin.com/in/captainamerica\n'
                       'Worked as: Staff Accountant, From Jan/01/1976 To Dec/31/1998 in New York, '
                       'NY, US \n'
                       'Worked as: Staff Accountant, From Jan/01/1999 To Jan/01/2002 in Pasadena, '
                       'AA, US \n'
                       'Worked as: Jigglypuff & Company, C.P.A, From Jan/01/2002 To Dec/31/2002 in '
                       'Pasadena, AA, US \n'
                       "Worked as: C.O.A.'s, From Jan/01/2003 To Dec/31/2003 in Agrabah, GM, US \n"
                       'Worked as: Staff Accountant, From Jan/01/2004 To Dec/31/2004 in New York, '
                       'NY, US \n'
                       'Gap in CV for 366 days\n'
                       'Worked as: Wax Preparer, From Jan/01/2006 To Dec/31/2006 in Agrabah, GM, '
                       'US \n'
                       "Worked as: C.O.A.'s, From Jan/01/2007 To Dec/31/2007 in Agrabah, GM, US \n"
                       'Worked as: Staff Accountant, From Jan/01/2008 To Dec/31/2008 in Agrabah, GM, '
                       'US \n']

candidates_info = [{'experience': [{'company_normalized_name': 'Valley Wastements', 'last_job': True,
                                    'company_name': 'Valley Wastements Inc', 'position_type': 'directHire',
                                    'duration_in_month': 11, 'current_job': False, 'title': 'Staff Accountant',
                                    'start_date': 'Jan/01/2008', 'same_company': False,
                                    'description_short': "1. Forget Purchase requisitions', Purchase orders and order materials;\n2. Physical count Spiderwebs;\n3. Adjust Spiderwebs balances and prices;\n4. Forget voucher package;\n5. Other administrative duties;",
                                    'company_details': {'company_type': 'Privately Held',
                                                        'company': 'Valley Wastements',
                                                        '_id': '54aef31217252229a56a86a4',
                                                        'company_url': '/company/Valley-Wastements?trk=ppro_cprof',
                                                        'number_of_time_seen': 13, 'industry': 'Real Estate industry',
                                                        'size': ' 11-50 employees'}, 'end_date': 'Dec/31/2008',
                                    'employer_org_name': 'Valley Wastements Inc',
                                    'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                                                 'short_display_address': 'Agrabah, GM, US'},
                                    'description': "2008 Valley Wastements Inc.\t\tAgrabah, GM.\nStaff Accountant:\n1. Forget Purchase requisitions', Purchase orders and order materials;\n2. Physical count Spiderwebs;\n3. Adjust Spiderwebs balances and prices;\n4. Forget voucher package;\n5. Other administrative duties;"},
                                   {'company_normalized_name': "Lion's King", 'company_name': "Lion's King",
                                    'position_type': 'directHire', 'duration_in_month': 11, 'current_job': False,
                                    'title': "C.O.A.'s", 'start_date': 'Jan/01/2007', 'same_company': False,
                                    'description_short': 'Staff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles\n5. Forget Wax returns;\n6. Perform other administrative duties;',
                                    'company_details': None, 'end_date': 'Dec/31/2007',
                                    'employer_org_name': "Lion's King",
                                    'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                                                 'short_display_address': 'Agrabah, GM, US'},
                                    'description': "2007 Lion's King service, C.O.A.'s\t\tAgrabah, GM.\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles\n5. Forget Wax returns;\n6. Perform other administrative duties;"},
                                   {'company_normalized_name': 'TaxTime', 'company_name': 'TaxTime',
                                    'position_type': 'directHire', 'duration_in_month': 11, 'current_job': False,
                                    'title': 'Wax Preparer', 'start_date': 'Jan/01/2006', 'same_company': False,
                                    'description_short': "1. Enter W'2's, 1099, 1098 an other Wax documents into Wax Software\n2. Forget Wax Returns\n3. Perform other administrative duties",
                                    'company_details': None, 'end_date': 'Dec/31/2006', 'employer_org_name': 'TaxTime',
                                    'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                                                 'short_display_address': 'Agrabah, GM, US'},
                                    'description': "2006 TaxTime\t\tAgrabah, GM.\nWax Preparer:\n1. Enter W'2's, 1099, 1098 an other Wax documents into Wax Software\n2. Forget Wax Returns\n3. Perform other administrative duties"},
                                   {'company_normalized_name': 'Forget Dig Statements',
                                    'company_name': 'Forget Dig Statements', 'position_type': 'directHire',
                                    'duration_in_month': 11, 'current_job': False, 'title': 'Staff Accountant',
                                    'start_date': 'Jan/01/2004', 'same_company': True,
                                    'description_short': '1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Forget Compilation or Review Report;\n7. Perform other administrative duties;',
                                    'company_details': None, 'end_date': 'Dec/31/2004',
                                    'employer_org_name': 'Forget Dig Statements',
                                    'location': {'region': 'NY', 'country_code': 'US', 'municipality': 'New York',
                                                 'short_display_address': 'New York, NY, US'},
                                    'description': '2004 Donald Duck & Company, C.P.A,\t\tNew York, N.Y.\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Forget Compilation or Review Report;\n7. Perform other administrative duties;'},
                                   {'company_normalized_name': 'Forget Dig Statements',
                                    'company_name': 'Forget Dig Statements', 'position_type': 'directHire',
                                    'duration_in_month': 11, 'current_job': False,
                                    'title': 'Jigglypuff & Company, C.P.A', 'start_date': 'Jan/01/2002',
                                    'same_company': True,
                                    'description_short': 'Staff Accountant;\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;',
                                    'company_details': None, 'end_date': 'Dec/31/2002',
                                    'employer_org_name': 'Forget Dig Statements',
                                    'location': {'region': 'AA', 'country_code': 'US', 'municipality': 'Pasadena',
                                                 'short_display_address': 'Pasadena, AA, US'},
                                    'description': '2002 Jigglypuff & Company, C.O.A.\t\tPasadena New Mexico\nStaff Accountant;\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;'},
                                   {'company_normalized_name': 'Forgetfulness Kvuza',
                                    'company_name': 'Forgetfulness Kvuza', 'position_type': 'directHire',
                                    'duration_in_month': 11, 'current_job': False, 'title': "C.O.A.'s",
                                    'start_date': 'Jan/01/2003', 'same_company': False,
                                    'description_short': 'Staff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;',
                                    'company_details': None, 'end_date': 'Dec/31/2003',
                                    'employer_org_name': 'Forgetfulness Kvuza',
                                    'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                                                 'short_display_address': 'Agrabah, GM, US'},
                                    'description': "2003 Forgetfulness Kvuza, C.O.A.'s\t\tAgrabah, GM\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;"},
                                   {'company_normalized_name': 'Pasadena Public Schools',
                                    'company_name': 'Pasadena Public Schools', 'position_type': 'directHire',
                                    'duration_in_month': 36, 'current_job': False, 'title': 'Staff Accountant',
                                    'start_date': 'Jan/01/1999', 'same_company': False,
                                    'description_short': '1. Review vouchers to insure payment;\n2. Analysis, monitor and report expenditures;\n3. Forget and close out Budgets;\n4. Forget Journals entries as needed;',
                                    'company_details': {'company_type': 'Educational Institution',
                                                        'company': 'Pasadena Public Schools',
                                                        '_id': '54aef37a17252229a56c986e',
                                                        'company_url': '/company/Pasadena-public-schools?trk=ppro_cprof',
                                                        'number_of_time_seen': 384,
                                                        'industry': 'Primary/Secondary Education industry',
                                                        'size': ' 5001-10,000 employees'}, 'end_date': 'Jan/01/2002',
                                    'employer_org_name': 'Pasadena Public Schools',
                                    'location': {'region': 'AA', 'country_code': 'US', 'municipality': 'Pasadena',
                                                 'short_display_address': 'Pasadena, AA, US'},
                                    'description': '1999-2002 Pasadena Public Schools\t\tPasadena New Mexico\nStaff Accountant: Crystal Development\n1. Review vouchers to insure payment;\n2. Analysis, monitor and report expenditures;\n3. Forget and close out Budgets;\n4. Forget Journals entries as needed;'},
                                   {'company_normalized_name': 'New City Transit Authority',
                                    'company_name': 'New City Transit Authority', 'position_type': 'directHire',
                                    'duration_in_month': 275, 'current_job': False, 'title': 'Staff Accountant',
                                    'start_date': 'Jan/01/1976', 'same_company': False,
                                    'description_short': '1. Review vouchers to insure payment;\n2. Records balance and resolve difference;\n3. Compile data and Forget various reports;\n4. Forget various general ledger accounts;',
                                    'company_details': None, 'end_date': 'Dec/31/1998',
                                    'employer_org_name': 'New City Transit Authority',
                                    'location': {'region': 'NY', 'country_code': 'US', 'municipality': 'New York',
                                                 'short_display_address': 'New York, NY, US'},
                                    'description': '1976 - 1998 New City Transit Authority\t\tNew York, N.Y.\nStaff Accountant: smashing Department\n1. Review vouchers to insure payment;\n2. Records balance and resolve difference;\n3. Compile data and Forget various reports;\n4. Forget various general ledger accounts;'}],
                    'contact_info': {'location': {'latitude': 99.0124, 'longitude': -100.1471},
                                     'email': 'captainamerica@yahoo.com', 'phone': '123-456-7890',
                                     'postal_address': {'address_line': '3', 'country_code': 'US',
                                                        'postal_code': '98765', 'region': 'GM',
                                                        'municipality': 'Agrabah',
                                                        'short_display_address': 'Agrabah, GM, US'},
                                     'image_url': 'https://www.syfy.com/sites/syfy/files/styles/1200x680/public/2019/06/spider-man-original.jpg',
                                     'name': {'formatted_name': 'Clark L Kent', 'family_name': 'Kent',
                                              'middle_name': 'L', 'given_name': 'Clark'}}, 'military_history': None,
                    }]

experience = [{'company_normalized_name': 'Valley Wastements', 'last_job': True,
               'company_name': 'Valley Wastements Inc', 'position_type': 'directHire',
               'duration_in_month': 11, 'current_job': False, 'title': 'Staff Accountant',
               'start_date': 'Jan/01/2008', 'same_company': False,
               'description_short': "1. Forget Purchase requisitions', Purchase orders and order materials;\n2. Physical count Spiderwebs;\n3. Adjust Spiderwebs balances and prices;\n4. Forget voucher package;\n5. Other administrative duties;",
               'company_details': {'company_type': 'Privately Held',
                                   'company': 'Valley Wastements',
                                   '_id': '54aef31217252229a56a86a4',
                                   'company_url': '/company/Valley-Wastements?trk=ppro_cprof',
                                   'number_of_time_seen': 13, 'industry': 'Real Estate industry',
                                   'size': ' 11-50 employees'}, 'end_date': 'Dec/31/2008',
               'employer_org_name': 'Valley Wastements Inc',
               'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                            'short_display_address': 'Agrabah, GM, US'},
               'description': "2008 Valley Wastements Inc.\t\tAgrabah, GM.\nStaff Accountant:\n1. Forget Purchase requisitions', Purchase orders and order materials;\n2. Physical count Spiderwebs;\n3. Adjust Spiderwebs balances and prices;\n4. Forget voucher package;\n5. Other administrative duties;"},
              {'company_normalized_name': "Lion's King", 'company_name': "Lion's King",
               'position_type': 'directHire', 'duration_in_month': 11, 'current_job': False,
               'title': "C.O.A.'s", 'start_date': 'Jan/01/2007', 'same_company': False,
               'description_short': 'Staff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles\n5. Forget Wax returns;\n6. Perform other administrative duties;',
               'company_details': None, 'end_date': 'Dec/31/2007',
               'employer_org_name': "Lion's King",
               'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                            'short_display_address': 'Agrabah, GM, US'},
               'description': "2007 Lion's King service, C.O.A.'s\t\tAgrabah, GM.\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles\n5. Forget Wax returns;\n6. Perform other administrative duties;"},
              {'company_normalized_name': 'TaxTime', 'company_name': 'TaxTime',
               'position_type': 'directHire', 'duration_in_month': 11, 'current_job': False,
               'title': 'Wax Preparer', 'start_date': 'Jan/01/2006', 'same_company': False,
               'description_short': "1. Enter W'2's, 1099, 1098 an other Wax documents into Wax Software\n2. Forget Wax Returns\n3. Perform other administrative duties",
               'company_details': None, 'end_date': 'Dec/31/2006', 'employer_org_name': 'TaxTime',
               'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                            'short_display_address': 'Agrabah, GM, US'},
               'description': "2006 TaxTime\t\tAgrabah, GM.\nWax Preparer:\n1. Enter W'2's, 1099, 1098 an other Wax documents into Wax Software\n2. Forget Wax Returns\n3. Perform other administrative duties"},
              {'company_normalized_name': 'Forget Dig Statements',
               'company_name': 'Forget Dig Statements', 'position_type': 'directHire',
               'duration_in_month': 11, 'current_job': False, 'title': 'Staff Accountant',
               'start_date': 'Jan/01/2004', 'same_company': True,
               'description_short': '1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Forget Compilation or Review Report;\n7. Perform other administrative duties;',
               'company_details': None, 'end_date': 'Dec/31/2004',
               'employer_org_name': 'Forget Dig Statements',
               'location': {'region': 'NY', 'country_code': 'US', 'municipality': 'New York',
                            'short_display_address': 'New York, NY, US'},
               'description': '2004 Donald Duck & Company, C.P.A,\t\tNew York, N.Y.\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Forget Compilation or Review Report;\n7. Perform other administrative duties;'},
              {'company_normalized_name': 'Forget Dig Statements',
               'company_name': 'Forget Dig Statements', 'position_type': 'directHire',
               'duration_in_month': 11, 'current_job': False,
               'title': 'Jigglypuff & Company, C.P.A', 'start_date': 'Jan/01/2002',
               'same_company': True,
               'description_short': 'Staff Accountant;\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;',
               'company_details': None, 'end_date': 'Dec/31/2002',
               'employer_org_name': 'Forget Dig Statements',
               'location': {'region': 'AA', 'country_code': 'US', 'municipality': 'Pasadena',
                            'short_display_address': 'Pasadena, AA, US'},
               'description': '2002 Jigglypuff & Company, C.O.A.\t\tPasadena New Mexico\nStaff Accountant;\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;'},
              {'company_normalized_name': 'Forgetfulness Kvuza',
               'company_name': 'Forgetfulness Kvuza', 'position_type': 'directHire',
               'duration_in_month': 11, 'current_job': False, 'title': "C.O.A.'s",
               'start_date': 'Jan/01/2003', 'same_company': False,
               'description_short': 'Staff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;',
               'company_details': None, 'end_date': 'Dec/31/2003',
               'employer_org_name': 'Forgetfulness Kvuza',
               'location': {'region': 'GM', 'country_code': 'US', 'municipality': 'Agrabah',
                            'short_display_address': 'Agrabah, GM, US'},
               'description': "2003 Forgetfulness Kvuza, C.O.A.'s\t\tAgrabah, GM\nStaff Accountant:\n1. Enter checks and invoice into smashing system;\n2. Forget Dig Statements;\n3. Forget newspaper entries;\n4. Forget Outcome Statement, Balance Sheet and Statement of pickles;\n5. Forget Wax returns;\n6. Perform other administrative duties;"},
              {'company_normalized_name': 'Pasadena Public Schools',
               'company_name': 'Pasadena Public Schools', 'position_type': 'directHire',
               'duration_in_month': 36, 'current_job': False, 'title': 'Staff Accountant',
               'start_date': 'Jan/01/1999', 'same_company': False,
               'description_short': '1. Review vouchers to insure payment;\n2. Analysis, monitor and report expenditures;\n3. Forget and close out Budgets;\n4. Forget Journals entries as needed;',
               'company_details': {'company_type': 'Educational Institution',
                                   'company': 'Pasadena Public Schools',
                                   '_id': '54aef37a17252229a56c986e',
                                   'company_url': '/company/Pasadena-public-schools?trk=ppro_cprof',
                                   'number_of_time_seen': 384,
                                   'industry': 'Primary/Secondary Education industry',
                                   'size': ' 5001-10,000 employees'}, 'end_date': 'Jan/01/2002',
               'employer_org_name': 'Pasadena Public Schools',
               'location': {'region': 'AA', 'country_code': 'US', 'municipality': 'Pasadena',
                            'short_display_address': 'Pasadena, AA, US'},
               'description': '1999-2002 Pasadena Public Schools\t\tPasadena New Mexico\nStaff Accountant: Crystal Development\n1. Review vouchers to insure payment;\n2. Analysis, monitor and report expenditures;\n3. Forget and close out Budgets;\n4. Forget Journals entries as needed;'},
              {'company_normalized_name': 'New City Transit Authority',
               'company_name': 'New City Transit Authority', 'position_type': 'directHire',
               'duration_in_month': 275, 'current_job': False, 'title': 'Staff Accountant',
               'start_date': 'Jan/01/1976', 'same_company': False,
               'description_short': '1. Review vouchers to insure payment;\n2. Records balance and resolve difference;\n3. Compile data and Forget various reports;\n4. Forget various general ledger accounts;',
               'company_details': None, 'end_date': 'Dec/31/1998',
               'employer_org_name': 'New City Transit Authority',
               'location': {'region': 'NY', 'country_code': 'US', 'municipality': 'New York',
                            'short_display_address': 'New York, NY, US'},
               'description': '1976 - 1998 New City Transit Authority\t\tNew York, N.Y.\nStaff Accountant: smashing Department\n1. Review vouchers to insure payment;\n2. Records balance and resolve difference;\n3. Compile data and Forget various reports;\n4. Forget various general ledger accounts;'}]

expected_experience = [
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008', 'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US'},
    {'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007', 'EndDate': 'Dec/31/2007', 'Location': 'Agrabah, GM, US'},
    {'Role': 'Wax Preparer', 'StartDate': 'Jan/01/2006', 'EndDate': 'Dec/31/2006', 'Location': 'Agrabah, GM, US'},
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2004', 'EndDate': 'Dec/31/2004', 'Location': 'New York, NY, US'},
    {'Role': 'Jigglypuff & Company, C.P.A', 'StartDate': 'Jan/01/2002', 'EndDate': 'Dec/31/2002',
     'Location': 'Pasadena, AA, US'},
    {'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2003', 'EndDate': 'Dec/31/2003', 'Location': 'Agrabah, GM, US'},
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/1999', 'EndDate': 'Jan/01/2002', 'Location': 'Pasadena, AA, US'},
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/1976', 'EndDate': 'Dec/31/1998', 'Location': 'New York, NY, US'}]

experience_for_enrichment = [
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008', 'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US'},
    {'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007', 'EndDate': 'Dec/31/2006', 'Location': 'Agrabah, GM, US'}]

experience_for_enrichment_no_gap = [
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008', 'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US'},
    {'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007', 'EndDate': 'Dec/31/2007', 'Location': 'Agrabah, GM, US'}]

experience_for_enrichment_small_gap = [
    {'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008', 'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US'},
    {'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007', 'EndDate': 'Dec/20/2007', 'Location': 'Agrabah, GM, US'}]

expected_enriched_experience = [
    {'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US', 'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008'},
    {'EndDate': 'Dec/31/2006', 'Gap': '366 days', 'Location': 'Agrabah, GM, US', 'Role': "C.O.A.'s",
     'StartDate': 'Jan/01/2007'}]

expected_enriched_experience_no_gap = [
    {'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US', 'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008'},
    {'EndDate': 'Dec/31/2007', 'Location': 'Agrabah, GM, US', 'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007'}]

expected_enriched_experience_small_gap = [
    {'EndDate': 'Dec/31/2008', 'Location': 'Agrabah, GM, US', 'Role': 'Staff Accountant', 'StartDate': 'Jan/01/2008'},
    {'EndDate': 'Dec/20/2007', 'Location': 'Agrabah, GM, US', 'Role': "C.O.A.'s", 'StartDate': 'Jan/01/2007'}]
